/**
 * @file Automatically generated by barrelsby.
 */

export * from "./HelloWorldController";
export * from "./passeportController";
export * from "./taskController";
export * from "./userController";
